spring:
  application:
    name=pokedex:
  datasource:
    url: jdbc:postgresql://localhost:5432/desapega
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect