spring:
  application:
    name=pokedex:
  datasource:
    url: jdbc:postgresql://localhost:5432/desapega
    username: postgres
    password: net.net6910
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect